# Generated by Django 4.2.8 on 2024-01-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('second_name', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.IntegerField()),
                ('pic', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
