# Generated by Django 4.2.8 on 2024-01-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='def@email.com', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='pwd',
            field=models.CharField(default='pass', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='second_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
