# Generated by Django 4.2.8 on 2024-01-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_role_alter_user_second_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='second_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
