# Generated by Django 4.2.8 on 2024-01-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('pateint', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('chronic_diseases', models.TextField(blank=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('birthday_place', models.CharField(blank=True, max_length=100)),
                ('blood_type', models.CharField(blank=True, max_length=10)),
                ('parents_disease', models.TextField(blank=True)),
                ('marriage_status', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
