# Generated by Django 4.2.8 on 2024-01-27 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Record', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='pateint',
            new_name='patient',
        ),
    ]
