# Generated by Django 4.2.8 on 2024-01-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Record', '0002_rename_pateint_medicalrecord_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='birthday',
            field=models.TextField(blank=True, null=True),
        ),
    ]
